database:
  use: SQL
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin

options:
  key-slot:
    1:
      name: '快捷键 1'
    2:
      name: '快捷键 1'
    3:
      name: '快捷键 1'
    4:
      name: '快捷键 1'
    5:
      name: '快捷键 1'

# by chemdah
level:
  def0:
    min: 1
    max: 100
    experience: |
      if check &level <= 15 then {
        math &level * 2 + 7
      } else if check &level <= 30 then {
        math &level * 5 - 38
      } else {
        math &level * 9 - 158
      }
