database:
  use: SQL # SQLITE(coding...),SQL
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin

options:
  scope-threshold: [ 1.0,1.0,1.0 ]
  auto-save-flag-period: 60000
  grid-air:
    material: WHEAT_SEEDS
    name: '空技能'
  grid-interact-actions: [ RIGHT_CLICK_AIR , RIGHT_CLICK_BLOCK ]
  grid-actionbar: '{{ meta skill name }} Counting.{{ math meta skill countdown / 1000 }}s'
  infos:
    - ''
    - '&3&lPlanners Profile'
    - ''
    - '   &c&lName &7{{ player name }} &e&l& &7{{ profile job }}({{ profile level }})'
    - ''
    - '     &b&lMana &7{{scaled profile mana }}/{{ profile max-mana }}'
    - '     &d&lSkill points &7{{ profile point }}'
    - '     &6&lExperience &7{{ profile exp }}/{{ profile max-exp }}'
    - ''
    - ''
  regain-mana-period: 100
  regain-mana-eval: math profile level * 0.5
  upgrade-points: math &value * 2

