database:
  use: SQL
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin

options:
  scope-threshold: [ 1.0,1.0,1.0 ]
  auto-save-flag-period: 60000
  grid-air:
    material: WHEAT_SEEDS
    name: '空技能'
  grid-interact: RIGHT_CLICK_AIR
  grid-actionbar: '{{ meta skill name }} Counting.{{ math meta skill countdown / 1000 }}s'
  infos:
    - '----------------'
    - '§d{{ profile job }} §6{{ player name }}'
    - '§eLv§f.§6{{ profile level }} §eEXP§f: §6{{ profile exp }}§f/§6{{ profile max-exp }}'
    - '§bMana§f: §6{{ profile mana }}§f/§6{{ profile max-mana }}'
    - '§aSkill Point§f: §6{{ profile point }}'
    - '----------------'
  regain-mana-period: 100
  regain-mana-eval: math profile level * 0.5
# by chemdah
level:
  def0:
    min: 1
    max: 100
    experience: |
      if check &level <= 15 then {
        math &level * 2 + 7
      } else if check &level <= 30 then {
        math &level * 5 - 38
      } else {
        math &level * 9 - 158
      }
